# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68179d3b480d2ebdbda188700cbebe446e62dc8536e7731a23c97345febade4d5c09257719f79bb4b5dc9ab9a9b404c2a6eb6b57f22970a8289c62fc847a8493

test:
  secret_key_base: 5858ce5f897cde934b0ca39ac3e12ed7ae10cbc591b433a14723435c697cf412c99648d6ae1fd9dd26c83174c1c6e6b5042d1583921060ac9a24a4bd4084245a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
